# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24184baf86ea7323de464d38929850b68d87f812941fa6f7803e224eaf4d13a1db96761d6dda2a35a1111d50dafd6005cfec40c605effdb5e6dbf7b863f4149e

test:
  secret_key_base: 22d7f5c64bc7f3619f2d4608f23ee28258881fafaa1ce385be0192b757a7a430dae77343da153ca45fca7a0536d40b98c84ee4c444a12316bb6d89cb196867ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
